<a href="https://colab.research.google.com/github/imsumit8/python_beginner/blob/main/Numpy_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
a=np.arange(0,16)

In [3]:
a.reshape(8,-1)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [4]:
len(a)

16

In [5]:
a.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [7]:
b=a.reshape(4,-1)

In [8]:
len(b)

4

In [10]:
#Taking transpose
b.T

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

In [12]:
a=a.reshape(-1,2)
print(a)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]


In [13]:
a[0]

array([0, 1])

In [14]:
a[-1]

array([14, 15])

In [15]:
a[0][0]

0

In [16]:
a=np.arange(10,19).reshape(3,-1)

In [17]:
a

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [18]:
a[1][2]

15

In [19]:
a[0,0]

10

In [20]:
a[[2,0]]

array([[16, 17, 18],
       [10, 11, 12]])

In [21]:
m1=np.arange(20).reshape(4,5)

In [22]:
m1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [23]:
m1[0:2]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [24]:
m1[-2:]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [25]:
#m1[rows slicing,column slicing]

In [26]:
m1[-2:,1:]

array([[11, 12, 13, 14],
       [16, 17, 18, 19]])

In [27]:
m1[1:3,0:2]

array([[ 5,  6],
       [10, 11]])

In [29]:
m1[m1<10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:

#o/p is 1d
m1[m1%2==0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [32]:
a = np.array([0,1,2,3,4,5])
mask = (a%2 == 0)
a[mask] = -1
a

array([-1,  1, -1,  3, -1,  5])

In [35]:
a=np.arange(1,6)
a

array([1, 2, 3, 4, 5])

In [36]:
np.sum(a)

15

In [37]:
np.mean(a)

3.0

In [41]:
np.min(a)

1

In [42]:
np.max(a)

5

In [45]:
#sum across rows
np.sum(m1[0])

10

In [46]:
np.sum(m1,axis=1) #sum across rows

array([10, 35, 60, 85])

In [47]:
np.sum(m1,axis=0) #sum across columns

array([30, 34, 38, 42, 46])

In [48]:
np.mean(m1,axis=1)

array([ 2.,  7., 12., 17.])

In [49]:
# np.any(bool array) -> atleast one element need to be true
# np.all(bool array)

In [50]:
prices = np.array([50, 45, 25, 20, 35])

budget = 30

can_afford = np.any(budget > prices)

if can_afford == True:
    print("You can buy atleast 1 item on your list")

You can buy atleast 1 item on your list


In [51]:
np.any(budget > prices)

True

In [52]:
    a = np.array([0,2,3])
    b = np.array([1,3,5])
a>=b

array([False, False, False])

#Fitbit EDA

In [56]:
!gdown id=1vk1Pu0djiYcrdc85yUXZ_Rqq2oZNcohd


Access denied with the following error:

 	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses. 

You may still be able to access the file from the browser:

	 https://drive.google.com/uc?id=id=1vk1Pu0djiYcrdc85yUXZ_Rqq2oZNcohd 



In [58]:
data=np.loadtxt('fit.txt',dtype='str')

In [59]:
data.shape

(96, 6)

In [60]:
data[0]

array(['06-10-2017', '5464', 'Neutral', '181', '5', 'Inactive'],
      dtype='<U10')

In [61]:
data[-1]

array(['09-01-2018', '2203', 'Happy', '0', '5', 'Active'], dtype='<U10')

In [62]:
data[:5]

array([['06-10-2017', '5464', 'Neutral', '181', '5', 'Inactive'],
       ['07-10-2017', '6041', 'Sad', '197', '8', 'Inactive'],
       ['08-10-2017', '25', 'Sad', '0', '5', 'Inactive'],
       ['09-10-2017', '5461', 'Sad', '174', '4', 'Inactive'],
       ['10-10-2017', '6915', 'Neutral', '223', '5', 'Active']],
      dtype='<U10')

In [64]:
data.T

array([['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
        '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
        '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
        '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
        '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
        '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
        '30-10-2017', '31-10-2017', '01-11-2017', '02-11-2017',
        '03-11-2017', '04-11-2017', '05-11-2017', '06-11-2017',
        '07-11-2017', '08-11-2017', '09-11-2017', '10-11-2017',
        '11-11-2017', '12-11-2017', '13-11-2017', '14-11-2017',
        '15-11-2017', '16-11-2017', '17-11-2017', '18-11-2017',
        '19-11-2017', '20-11-2017', '21-11-2017', '22-11-2017',
        '23-11-2017', '24-11-2017', '25-11-2017', '26-11-2017',
        '27-11-2017', '28-11-2017', '29-11-2017', '30-11-2017',
        '01-12-2017', '02-12-2017', '03-12-2017', '04-12-2017',
        '05-12-2017', '06-12-2017', '07-

In [72]:
date,step_count,mood,calories_burnt,hours_of_sleep,activity_status=data.T

In [73]:
date

array(['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
       '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
       '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
       '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
       '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
       '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
       '30-10-2017', '31-10-2017', '01-11-2017', '02-11-2017',
       '03-11-2017', '04-11-2017', '05-11-2017', '06-11-2017',
       '07-11-2017', '08-11-2017', '09-11-2017', '10-11-2017',
       '11-11-2017', '12-11-2017', '13-11-2017', '14-11-2017',
       '15-11-2017', '16-11-2017', '17-11-2017', '18-11-2017',
       '19-11-2017', '20-11-2017', '21-11-2017', '22-11-2017',
       '23-11-2017', '24-11-2017', '25-11-2017', '26-11-2017',
       '27-11-2017', '28-11-2017', '29-11-2017', '30-11-2017',
       '01-12-2017', '02-12-2017', '03-12-2017', '04-12-2017',
       '05-12-2017', '06-12-2017', '07-12-2017', '08-12

In [74]:
step_count=step_count.astype('int')

In [75]:
np.mean(step_count)

2935.9375

In [76]:
hours_of_sleep=hours_of_sleep.astype('int')

In [77]:
np.mean(hours_of_sleep)

5.21875

In [80]:
hours_of_sleep[hours_of_sleep>7].size

11

In [83]:
mood[mood=='Happy'].size

40

In [84]:
step_count[mood=='Happy'].mean()

3392.725

In [85]:
step_count[mood=='Sad'].mean()

2103.0689655172414

In [86]:
mood[step_count>4000]

array(['Neutral', 'Sad', 'Sad', 'Neutral', 'Sad', 'Sad', 'Sad', 'Happy',
       'Neutral', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy',
       'Neutral', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Sad',
       'Happy', 'Happy', 'Neutral', 'Happy', 'Neutral', 'Neutral', 'Sad',
       'Happy', 'Neutral', 'Happy'], dtype='<U10')